version: "3.7"

services:
  db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password --general_log=ON
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3346:3346

  adminer:
    image: adminer
    restart: always
    ports:
      - 8282:8080
